name: Build and deploy ASP.Net Core app to Azure Web App - assetmanagement

on:
  push:
    branches:
      - dev
  workflow_dispatch:

jobs:
  build:
    runs-on: windows-latest

    steps:
      - uses: actions/checkout@v4
        with:
          ref: dev  # Ensure the correct branch is checked out

      - name: Debug:list-files
        run: dir /s src/Presentation/API  # Debugging step to verify the file structure

      - name: Set up .NET Core
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: '8.x'

      - name: Build with dotnet
        run: dotnet build src/Presentation/API/ASM.WebApi.csproj --configuration Release

      - name: dotnet publish
        run: dotnet publish src/Presentation/API/ASM.WebApi.csproj -c Release -o "${{env.DOTNET_ROOT}}/myapp"

      - name: Upload artifact for deployment job
        uses: actions/upload-artifact@v4
        with:
          name: .net-app
          path: ${{env.DOTNET_ROOT}}/myapp

  deploy:
    runs-on: windows-latest
    needs: build
    environment:
      name: 'Production'
      url: ${{ steps.deploy-to-webapp.outputs.webapp-url }}
    permissions:
      id-token: write #This is required for requesting the JWT

    steps:
      - name: Download artifact from build job
        uses: actions/download-artifact@v4
        with:
          name: .net-app

      - name: Login to Azure
        uses: azure/login@v2
        with:
          client-id: ${{ secrets.AZUREAPPSERVICE_CLIENTID_F51738DDF27243B5B53F940B4F90281B }}
          tenant-id: ${{ secrets.AZUREAPPSERVICE_TENANTID_C9627C8A8AA3B164A86696B37 }}
          subscription-id: ${{ secrets.AZUREAPPSERVICE_SUBSCRIPTIONID_01BD9BCFE8324C5998016B639DDCBE8A }}

      - name: Deploy to Azure Web App
        id: deploy-to-webapp
        uses: azure/webapps-deploy@v3
        with:
          app-name: 'assetmanagement'
          slot-name: 'Production'
          package: .
